steps:
  # Step 1: Deploy the Network/Base stack
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy GKE'
    entrypoint: 'gcloud'
    args: 
      - 'infra-manager'
      - 'deployments'
      - 'apply'
      - 'projects/${PROJECT_ID}/locations/${_REGION}/deployments/base-network'
      - '--service-account=projects/${PROJECT_ID}/serviceAccounts/infra-manager-runner@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--git-source-repo=${_REPO_URL}'
      - '--git-source-directory=cloud/gcp/gke'
      - '--git-source-ref=master'
      - '--input-values=project_id=${PROJECT_ID},region=${_REGION}'

  # Step 2: Deploy the GKE/Cluster stack (Wait for Network)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    id: Gitops Platform
    args:
      - 'infra-manager'
      - 'deployments'
      - 'apply'
      - 'projects/${PROJECT_ID}/locations/${_REGION}/deployments/gke-cluster'
      - '--service-account=projects/${PROJECT_ID}/serviceAccounts/infra-manager-runner@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--git-source-repo=${_REPO_URL}'
      - '--git-source-directory=cloud/gcp/gitops/platform'
      - '--git-source-ref=master'
      - '--input-values=project_id=${PROJECT_ID},region=${_REGION}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  _REPO_URL: 'https://github.com/your-org/your-repo'
  _STATE_BUCKET: ''