steps:
  # Step 0: Build Helm Dependencies
  - name: 'alpine/helm:3.17.1'
    id: 'Build Helm Deps'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd cloud/terraform/gcp/gke/helm/gateway-infra && helm dependency build

  # Step 1: Security Scan (Checkov)
  - name: 'bridgecrew/checkov:latest'
    id: 'Security Scan - Checkov'
    args:
      - '--directory=cloud/terraform'
      - '--download-external-modules'
      - '--compact'
      - '--soft-fail'

  # Step 2: Security Scan (Trivy)
  - name: 'aquasec/trivy:latest'
    id: 'Security Scan - Trivy'
    entrypoint: 'trivy'
    args:
      - 'fs'
      - '.'
      - '--severity=HIGH,CRITICAL'
      - '--exit-code=0'

  # Step 3: Deploy the Network/Base stack
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy GKE'
    entrypoint: 'gcloud'
    args: 
      - 'infra-manager'
      - 'deployments'
      - 'apply'
      - 'projects/${PROJECT_ID}/locations/${_REGION}/deployments/gke-network'
      - '--service-account=projects/${PROJECT_ID}/serviceAccounts/infra-manager-runner@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--git-source-repo=${_REPO_URL}'
      - '--git-source-directory=cloud/terraform/gcp/gke'
      - '--git-source-ref=master'
      - '--inputs-file=terraform.tfvars'
      - '--input-values=project_id=${PROJECT_ID},region=${_REGION},state_bucket=${_STATE_BUCKET}'

  # Step 4: Deploy the GKE/Cluster stack
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    id: Gitops Platform
    args:
      - 'infra-manager'
      - 'deployments'
      - 'apply'
      - 'projects/${PROJECT_ID}/locations/${_REGION}/deployments/gitops-platform'
      - '--service-account=projects/${PROJECT_ID}/serviceAccounts/infra-manager-runner@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--git-source-repo=${_REPO_URL}'
      - '--git-source-directory=cloud/terraform/gcp/gitops/platform'
      - '--git-source-ref=master'
      - '--input-values=project_id=${PROJECT_ID},region=${_REGION},state_bucket=${_STATE_BUCKET}'

substitutions:
  _REGION: 'us-central1'
  _REPO_URL: 'https://github.com/your-org/your-repo'
  _STATE_BUCKET: ''
