# 1. SecretStore for Liferay License (GCP Secret Manager)
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
    name: liferay-license-secret-store
    namespace: {{ include "liferay.namespace" . | quote }}
spec:
    provider:
        gcpsm:
            projectID: {{ .Values.global.projectID | quote }}
---
# 2. ExternalSecret for Liferay License
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: liferay-license
    namespace: {{ include "liferay.namespace" . | quote }}
spec:
    refreshInterval: 1h
    secretStoreRef:
        kind: SecretStore
        name: liferay-license-secret-store
    target:
        name: liferay-license
        creationPolicy: Owner
    data:
        -   secretKey: license
            remoteRef:
                key: liferay-cloud-native-liferay-license-xml
