locals {
	common_labels={
		"app.kubernetes.io/managed-by"=local.terraform_manager_name
		"environment"="internal"
	}
	terraform_manager_name="liferay-cloud-native-terraform"
}

resource "kubernetes_namespace_v1" "kyverno" {
	metadata {
		labels=local.common_labels
		name=var.kyverno_namespace
	}
}

resource "helm_release" "kyverno" {
	chart="kyverno"
	name="kyverno"
	namespace=kubernetes_namespace_v1.kyverno.metadata[0].name
	repository="https://kyverno.github.io/kyverno/"
	version="3.3.4"

	values=[
		yamlencode({
			admissionController={
				container={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="100m"
							memory="256Mi"
						}
					}
				}
				replicas=2
			}
			backgroundController={
				container={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="100m"
							memory="256Mi"
						}
					}
				}
				replicas=2
			}
			cleanupController={
				container={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="100m"
							memory="256Mi"
						}
					}
				}
				replicas=2
			}
			reportsController={
				container={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="100m"
							memory="256Mi"
						}
					}
				}
				replicas=2
			}
		})
	]
}
