resource "helm_release" "nginx_ingress" {
	chart="ingress-nginx"
	cleanup_on_fail=true
	count=var.networking_mode == "ingress" ? 1 : 0
	create_namespace=true
	depends_on=[
		module.gke,
	]
	name="nginx-ingress-controller"
	namespace="nginx-ingress-controller"
	replace=true
	repository="https://kubernetes.github.io/ingress-nginx"
	timeout=900
	upgrade_install=false
	values=[
		yamlencode({
			controller={
				config={
					"compute-full-forwarded-for"="true"
					"use-forwarded-headers"="true"
					"use-proxy-protocol"="false",
				}
				resources={
					limits={
						cpu="500m"
						memory="512Mi",
					}
					requests={
						cpu="100m"
						memory="256Mi",
					}
				}
				service={
					annotations={
						"cloud.google.com/load-balancer-type"="Internal",
					}
					type="ClusterIP",
				},
			},
		}),
	]
	version="4.11.3"
	wait=true
}
