gcp:
    projectId: ""
    projectNumber: ""
    clusterName: ""
    networkName: ""
    subnetworkName: ""

crossplaneNamespace: crossplane-system
deploymentName: ""
rootDomain: ""
liferayServiceAccountRoleName: ""
